# Generated by Django 4.0.3 on 2022-03-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=128)),
                ('field2', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('field1', 'field2'),
            },
        ),
        migrations.CreateModel(
            name='MyModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=128)),
                ('field2', models.CharField(max_length=128)),
                ('mymodel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue109.mymodel1')),
            ],
            options={
                'ordering': ('field1', 'mymodel1__field1'),
            },
        ),
    ]
